### PR TITLE
modified the color of the red nav buttons on the bottom

### PR DESCRIPTION
**Pull request by miomech**
modified the buttons from blue to red to make them easier to see.

### CODE REVIEW

**Comment by miomech** [comment]
Looks good to me? any suggestions?

**Comment by NadaMech** [comment]
ight

**Comment by datboimech** [comment]
i don't know about this

**Review by miomech — COMMENTED** [review]
I like the new color

**Review by datboimech — COMMENTED** [review]
Decent

**Review by NadaMech — COMMENTED** [review]
good change for eyes

**Pull request merged**
